### ISSUE TITLE
DOMException

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [Veams/veams-query#2]
With the latest version Veams-Query is throwing an error when selecting an empty object: 

`DOMException: Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.`

**Comment by andy-gutsche** [comment]
What is the expected behavior in that case? An empty object is indeed no valid DOM selector, therefore the error message thrown by the browser makes totally sense to me. jQuery returns `undefined` for `jQuery()` and `jQuery({})`.

**Comment by Sebastian-Fitzner** [comment]
It returns undefined, but creates an object which has all methods available. Perhaps can leave it out and only use `$();`.  Will give it a try ...

**Comment by Sebastian-Fitzner** [comment]
So, it is not working with an empty collection. in jQuery it is working ...

**Comment by andy-gutsche** [comment]
This is out of scope in terms of the original intention for that module. The event system is only meant to deal with Objects that inplement the EventTarget interface.
