### ISSUE TITLE
Get not the current computed styles like JQuery

### ISSUE THREAD

**Issue by Sw0rdiX** [Veams/veams-query#3]
https://github.com/Veams/veams-query/blob/2a10b03c8564a88d1bf5efd13b4e91b854fe4b2e/src/veams-query.js#L544-L558

all elm.stlye attributes r only inline-styles not the hole computed styles.

example : 
return this[0].style[cssProp]; should return :  return getComputedStyle(this[0]).cssProp;

**Comment by andy-gutsche** [comment]
Fixed in v2.2.5. Thanks for the hint!
